<script src="<?= base_url('assets/js/jquery-3.6.0.min.js')?>"></script>
<script src="<?= base_url('assets/js/feather.min.js')?>"></script>
<script src="<?= base_url('assets/js/jquery.slimscroll.min.js')?>"></script>
<script src="<?= base_url('assets/js/jquery.dataTables.min.js')?>"></script>
<script src="<?= base_url('assets/js/dataTables.bootstrap4.min.js')?>"></script>
<script src="<?= base_url('assets/plugins/select2/js/select2.min.js')?>"></script>
<script src="<?= base_url('assets/js/moment.min.js')?>"></script>
<script src="<?= base_url('assets/js/bootstrap-datetimepicker.min.js')?>"></script>
<script src="<?= base_url('assets/js/bootstrap.bundle.min.js')?>"></script>
<script src="<?= base_url('assets/js/tinymce/tinymce.min.js')?>"></script>
<script src="<?= base_url('assets/plugins/sweetalert/sweetalerts.min.js')?>"></script>
<script src="<?= base_url('assets/plugins/apexchart/apexcharts.min.js')?>"></script>
<script src="<?= base_url('assets/plugins/apexchart/chart-data.js')?>"></script>
<script src="<?= base_url('assets/plugins/select2/js/custom-select.js')?>"></script>
<script src="<?= base_url('assets/plugins/sweetalert/sweetalert2.all.min.js')?>"></script>
<script src="<?= base_url('assets/js/script.js')?>"></script>